# https://github.com/IQSS/dataverse-docker/blob/master/docker-compose.yml
# https://knplabs.com/en/blog/how-to-handle-https-with-docker-compose-and-mkcert-for-local-development/

services:
  proxy:
    container_name: ${COMPOSE_PROJECT_NAME}-proxy
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.proxy
      args:
        APPSETTING_SERVICE_PROXY_BASE_IMAGE: ${APPSETTING_SERVICE_PROXY_BASE_IMAGE}
    restart: always
    ports:
      - 80:80
      - 8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certs:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${APPSETTING_SERVICE_PROXY_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web"
      - "traefik.port=8080"
    networks:
      - ${COMPOSE_PROJECT_NAME}

networks:
  dm_proxy:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME} 