ARG APPSETTING_SERVICE_MEMCACHED_BASE_IMAGE
FROM $APPSETTING_SERVICE_MEMCACHED_BASE_IMAGE

# user:
USER root
ADD ./templates/bashrc /root/.bashrc

# packages:
RUN apt-get update
RUN apt-get install -y netcat-openbsd

(({}.var.extra_commands))