pma:
  container_name: ${COMPOSE_PROJECT_NAME}-pma
  build:
    context: .
    dockerfile: ./templates/dockerfile.pma
    args:
      APPSETTING_SERVICE_PMA_BASE_IMAGE: ${APPSETTING_SERVICE_PMA_BASE_IMAGE}
  links:
    - db
  environment:
    MYSQL_ROOT_PASSWORD: root
    PMA_HOST: ${COMPOSE_PROJECT_NAME}-db
    PMA_USER: ${APPSETTING_SERVICE_DB_USER}
    PMA_PASSWORD: ${APPSETTING_SERVICE_DB_PASS}
  restart: unless-stopped
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pma.rule=Host(`${APPSETTING_SERVICE_PMA_HOST_UI}`)"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pma.tls=true"
  networks:
    - dm_proxy
  depends_on:
    - db