# REF: https://medium.com/@mehdi_hosseini/how-to-link-multiple-docker-compose-files-7250f10063a9#:~:text=By%20using%20the%20%2Df%20option,complexity%20of%20the%20overall%20configuration.
#
# services:
# 
#   redis:
#     container_name: ${COMPOSE_PROJECT_NAME}-redis
#     build:
#       context: .
#       dockerfile: ./custom/dockerfile/Dockerfile.redis
#       args:
#         APPSETTING_SERVICE_REDIS_BASE_IMAGE: ${APPSETTING_SERVICE_REDIS_BASE_IMAGE}
#     restart: unless-stopped
#     labels:
#       - "traefik.http.services.${COMPOSE_PROJECT_NAME}_db.loadbalancer.server.port=6379"
#     networks:
#       - dm_proxy
# 
#   memcached:
#     container_name: ${COMPOSE_PROJECT_NAME}-memcached
#     build:
#       context: .
#       dockerfile: ./custom/dockerfile/Dockerfile.memcached
#       args:
#         APPSETTING_SERVICE_MEMCACHED_BASE_IMAGE: ${APPSETTING_SERVICE_MEMCACHED_BASE_IMAGE}
#     restart: unless-stopped
#     labels:
#       - "traefik.http.services.${COMPOSE_PROJECT_NAME}_db.loadbalancer.server.port=11211"
#     networks:
#       - dm_proxy
# 
#   www:
#     extends:
#       file: docker-compose.common.local.yml
#       service: www
#     build:
#       context: .
#       dockerfile: ./custom/dockerfile/Dockerfile.www