# https://github.com/IQSS/dataverse-docker/blob/master/docker-compose.yml
# https://knplabs.com/en/blog/how-to-handle-https-with-docker-compose-and-mkcert-for-local-development/

networks:
  dm_proxy:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME} 

services: (({}.var.services))
