mailhog:
  container_name: ${COMPOSE_PROJECT_NAME}-mailhog
  build:
    context: .
    dockerfile: ./templates/dockerfile/mailhog
    args:
      APPSETTING_SERVICE_MAILHOG_BASE_IMAGE: ${APPSETTING_SERVICE_MAILHOG_BASE_IMAGE}
  restart: unless-stopped
  ports: [ "1025:8025" ]