redis:
  container_name: ${COMPOSE_PROJECT_NAME}-redis
  build:
    context: .
    dockerfile: ./templates/dockerfile/redis
    args:
      APPSETTING_SERVICE_REDIS_BASE_IMAGE: ${APPSETTING_SERVICE_REDIS_BASE_IMAGE}
  ports: [ "6379:6379" ]