memcached:
  container_name: ${COMPOSE_PROJECT_NAME}-memcached
  build:
    context: .
    dockerfile: ./templates/dockerfile/memcached
    args:
      APPSETTING_SERVICE_MEMCACHED_BASE_IMAGE: ${APPSETTING_SERVICE_MEMCACHED_BASE_IMAGE}
  restart: unless-stopped
  ports: [ "11311:11211" ]