pma:
  container_name: ${COMPOSE_PROJECT_NAME}-pma
  build:
    context: .
    dockerfile: ./templates/dockerfile/pma
    args:
      APPSETTING_SERVICE_PMA_BASE_IMAGE: ${APPSETTING_SERVICE_PMA_BASE_IMAGE}
  links:
    - db
  environment:
    MYSQL_ROOT_PASSWORD: root
    PMA_HOST: ${COMPOSE_PROJECT_NAME}-db
    PMA_USER: ${APPSETTING_SERVICE_DB_USER}
    PMA_PASSWORD: ${APPSETTING_SERVICE_DB_PASS}
  depends_on:
    - db
  ports: [ "8080:80" ]