solr:
  container_name: ${COMPOSE_PROJECT_NAME}-solr
  build:
    context: .
    dockerfile: ./templates/dockerfile/solr
    args:
      APPSETTING_SERVICE_SOLR_BASE_IMAGE: ${APPSETTING_SERVICE_SOLR_BASE_IMAGE}
  volumes:
    - solr_data:/var/solr
  command:
    - solr-precreate
    - ${APPSETTING_SERVICE_SOLR_HOST_SV}
  ports: [ "8983:8983" ]