help: Accede a servidor remoto
example:
- (({}.tmp.proc.sig))

task:
  require:
    config:
      - .*(\.dev|\.test|\.pre|\.prod) origin
    args: {}
    opt:
      user:
        type: String
        default:
    settings: {}
  do:
    - { event: 'origin startup' }
    -
      call: exec
      args:
        user: (({origin}.hook.call[dm.access].exec.user))
        pass: (({origin}.hook.call[dm.access].exec.pass))
        default_options: "-t"
        cmd: /bin/bash
        out: true
    - { event: 'origin windup' }
 