help: Despliega código
example:
- (({}.tmp.proc.sig))

task:
  require:
    config:
      - .*(\.local|\.dev|\.test|\.pre) origin
    args: {}
    opt: {}
    settings: {}
  do:
    - { event: 'origin startup' }
    - { event: 'origin windup' }