help: Apaga servicios
example:
- (({}.tmp.proc.sig))

task:
  require:
    config:
      - .*(\.local) origin
  do:
    - { event: 'origin startup' }
    - { call: dm.setUp }
    -
      call: exec
      args:
        cd: (({}.var.setup_home_root))
        cmd: export COMPOSE_PROJECT_NAME=(({origin}._tag)); export APPSETTING_UID=(({}.user.uid)); export APPSETTING_GID=(({}.user.gid)); export APPSETTING_USER=(({}.user.username)); export APPSETTING_ENV=(({origin}._env)); docker compose --env-file .env down --remove-orphans
        out: true
    - { event: 'origin windup' }

# docker container stop $(docker network inspect --format '{{range $cid,$v := .Containers}}{{printf "%s: %s\n" $cid $v.Name}}{{end}}' "dm_network-dm_seidor_frontend" | awk -F: '{ print $2 }' | xargs)