help: Ejecuta comando
example:
- (({}.tmp.proc.sig)) www whoami
- (({}.tmp.proc.sig)) www ls -la
- (({}.tmp.proc.sig)) www vendor/bin/phpstan.phar analyze web/modules/custom --memory-limit=256M

task:
  require:
    config:
      - .*(\.local|\.dev|\.test|\.pre) origin
    args:
      command:
        type: .*
        default: /bin/bash
    opt:
      user:
        type: String
        default:
  do:
    - { event: 'origin startup' }
    - 
      check:
        data:
          -
            key: (({origin}._env))
            is: equal
            value: local
        true:
          -
            call: exec
            args:
              cmd: (({}.exec)) (({origin}._config_name)) service.exec www (({}.args.command))
              out: true
        false:
          -
            call: exec
            args:
              cmd: (({}.args._))
              out: true
    - { event: 'origin windup' }
 