help: Obtiene accesos
example:
- (({}.tmp.proc.sig))

task:
  require:
    config: []
    args: {}
    settings: {}
  do:
    - { event: 'origin startup' }
    -
      call: exec
      args:
        cmd: (({}.exec)) @*..server.access
        out: true
    - { event: 'origin windup' }
 