help: Ejecuta test
example:
- (({}.tmp.proc.sig))

task:
  complete: []
  require:
    config: []
    args: {}
    opt: {}
  do:
    - { event: 'origin startup' }
    #- call: dm.main
    #- call: out
    - { call: exec, args: { cmd: "watch -n 0.5 ls -la", out: true }}
    - { event: 'origin windup' }

