help: Muestra mensajes de depuración de Nginx
example:
- (({}.tmp.proc.sig))

task:
  require:
    config:
      - .*(\.local|\.dev|\.test|\.pre|\.stage) origin
  do:
    - { event: 'origin startup' }
    -
      call: exec
      args:
        cmd: (({}.exec)) (({origin}._config_name)) exec sudo tail -f /var/log/(({origin}.appsetting.service.www.webserver))/error.log
        out: true
    - { event: 'origin windup' }
    
