www:
  container_name: ${COMPOSE_PROJECT_NAME}-www
  hostname: ${COMPOSE_PROJECT_NAME}-www
  build:
    context: .
    dockerfile: ./templates/dockerfile/www
    args:
      APPSETTING_USER: ${APPSETTING_USER}
      APPSETTING_GID: ${APPSETTING_GID}
      APPSETTING_UID: ${APPSETTING_UID}
      APPSETTING_SERVICE_WWW_BASE_IMAGE: ${APPSETTING_SERVICE_WWW_BASE_IMAGE}
      APPSETTING_SERVICE_WWW_PHP_RELEASE: ${APPSETTING_SERVICE_WWW_PHP_RELEASE}
      APPSETTING_SERVICE_WWW_COMPOSER_RELEASE: ${APPSETTING_SERVICE_WWW_COMPOSER_RELEASE}
      APPSETTING_SERVICE_WWW_WEBSERVER: ${APPSETTING_SERVICE_WWW_WEBSERVER}
  #environment: (({}.var.env_docker_compose))
  env_file: .env
  working_dir: ${APPSETTING_SERVICE_WWW_TARGET}
  volumes:
    - 
      consistency: cached
      source: ${APPSETTING_SERVICE_WWW_SOURCE}
      target: ${APPSETTING_SERVICE_WWW_TARGET}
      type: bind
    - 
      consistency: cached
      source: ./templates/sh
      target: /home/${APPSETTING_USER}/sh
      type: bind
  healthcheck:
    interval: 1s
    retries: 120
    start_period: 2m0s
    timeout: 2m0s
  restart: unless-stopped
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_www.tls=true"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_www.rule=Host(`${APPSETTING_SERVICE_WWW_HOST_UI}`)"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_www.entrypoints=websecure"
    - "traefik.http.services.${COMPOSE_PROJECT_NAME}_www.loadbalancer.server.port=443"
    - "traefik.http.services.${COMPOSE_PROJECT_NAME}_www.loadbalancer.server.port=80"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  networks:
    - dm_proxy