solr:
  container_name: ${COMPOSE_PROJECT_NAME}-solr
  build:
    context: .
    dockerfile: ./templates/dockerfile/solr
    args:
      APPSETTING_SERVICE_SOLR_BASE_IMAGE: ${APPSETTING_SERVICE_SOLR_BASE_IMAGE}
  volumes:
    - solr_data:/var/solr
  command:
    - solr-precreate
    - ${APPSETTING_SERVICE_SOLR_HOST_SV}
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_solr.tls=true"
    - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_solr.rule=Host(`${APPSETTING_SERVICE_SOLR_HOST_UI}`)"
    - "traefik.http.services.${COMPOSE_PROJECT_NAME}_solr.loadbalancer.server.port=8983"
  networks:
    - dm_proxy