doc:
  container_name: ${APPSETTING_SERVICE_DOC_HOST}
  hostname: ${APPSETTING_SERVICE_DOC_HOST}
  build:
    context: .
    dockerfile: ./templates/dockerfile/doc
    args:
      APPSETTING_SERVICE_DOC_BASE_IMAGE: ${APPSETTING_SERVICE_DOC_BASE_IMAGE}
  env_file:
    - ../.env
    - .env
  volumes:
    -
      consistency: cached
      source: ../
      target: ${APPSETTING_SERVICE_WWW_TARGET}
      type: bind
  working_dir: ${APPSETTING_SERVICE_WWW_TARGET}/doc
  user: ${APPSETTING_UID}:${APPSETTING_GID}
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${APPSETTING_SERVICE_DOC_HOST}.rule=${APPSETTING_PROXY_SERVICE_DOC_RULE_HOST}"
    - "traefik.http.routers.${APPSETTING_SERVICE_DOC_HOST}.tls=true"
    - "traefik.http.services.${APPSETTING_SERVICE_DOC_HOST}.loadbalancer.server.port=3000"
  networks:
    - dmproxy