beszel:
  container_name: ${APPSETTING_SERVICE_BESZEL_HOST}
  hostname: ${APPSETTING_SERVICE_BESZEL_HOST}
  build:
    context: .
    dockerfile: ./templates/dockerfile/beszel
    args:
      APPSETTING_SERVICE_BESZEL_BASE_IMAGE: ${APPSETTING_SERVICE_BESZEL_BASE_IMAGE}
  restart: unless-stopped
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    APP_URL: ${APPSETTING_SERVICE_BESZEL_APP_URL:-http://127.0.0.1:8090}
  volumes:
    - beszel_data:/beszel_data
  ports:
    - "127.0.0.1:8090:8090"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${APPSETTING_SERVICE_BESZEL_HOST}.rule=${APPSETTING_PROXY_SERVICE_BESZEL_RULE_HOST}"
    - "traefik.http.routers.${APPSETTING_SERVICE_BESZEL_HOST}.tls=true"
    - "traefik.http.services.${APPSETTING_SERVICE_BESZEL_HOST}.loadbalancer.server.port=8090"
  networks:
    - dmproxy