# Login:
# 1. admin/admin
# 2. admin/Drupal$Sonar1
sonarqube:
  container_name: ${COMPOSE_PROJECT_NAME}-sonarqube
  build:
    context: .
    dockerfile: ./templates/dockerfile/sonarqube
    args:
      APPSETTING_SERVICE_SONARQUBE_BASE_IMAGE: ${APPSETTING_SERVICE_SONARQUBE_BASE_IMAGE}
  environment:
    SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
    SONAR_JDBC_USERNAME: sonar
    SONAR_JDBC_PASSWORD: sonar
  volumes:
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_logs:/opt/sonarqube/logs
  ports: [ "9000:9000" ]